name: Testing Build
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_apiKey: ${{secrets.API_KEY}}
          envkey_REACT_APP_authDomain: ${{secrets.AUTH_DOMAIN}}
          envkey_REACT_APP_projectId: ${{secrets.PROJECT_ID}}
          envkey_REACT_APP_storageBucket: ${{secrets.STORAGE_BUCKET}}
          envkey_REACT_APP_messagingSenderId: ${{secrets.SENDER_ID}}
          envkey_REACT_APP_appId: ${{secrets.APP_ID}}

          file_name: .env
          fail_on_empty: true

      - run: npm ci
      - run: npm run build
      - run: ls -a
