name: Testing Build
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build
        env: 
          REACT_APP_apiKey: ${{secrets.API_KEY}}
          REACT_APP_authDomain: ${{secrets.AUTH_DOMAIN}}
          REACT_APP_projectId: ${{secrets.PROJECT_ID}}
          REACT_APP_storageBucket: ${{secrets.STORAGE_BUCKET}}
          REACT_APP_messagingSenderId: ${{secrets.SENDER_ID}}
          REACT_APP_appId: ${{secrets.APP_ID}}

      - run: ls -a
      - run: cat .env
